config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static#home'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :wineries
  resources :regions do
    resources :wineries, only: [:new, :create, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :wineries

    validates :name, presence: true, uniqueness: true

    accepts_nested_attributes_for :wineries, reject_if: :all_blank
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wineries
  has_many :regions, through: :wineries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

         def self.new_with_session(params, session)
          super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
              user.email = data["email"] if user.email.blank?
            end
          end
        end
        
        def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            user.name = auth.info.name   # assuming the user model has a name
            user.image = auth.info.image # assuming the user model has an image
          end
        end
end

app/models/winery.rb
class Winery < ApplicationRecord
  belongs_to :region
  belongs_to :user
 
  validates :name, presence: true, uniqueness: true, length: { in: 3..50 }
  validates :website, presence: true
  validates :phone, presence: true

  accepts_nested_attributes_for :region, reject_if: :all_blank

  def region_name
    self.region ? self.region.name : "Region not available"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
    

    def index
        @regions = Region.all
    end

    def show
        @region = Region.find_by_id(params[:id])
    end
    
    def new
        @region = Region.new
        @region.wineries.build
        @region.wineries.build
        @region.wineries.build
    end

    def create
        @region = Region.new(region_params)

        if @region.save
            redirect_to wineries_path
        else
            render :new
        end
    end

    private
        def region_params
            params.require(:region).permit(:name, wineries_attributes: [:name, :website, :phone])
        end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
        render layout: "home_page_layout"
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController
    before_action :find_region, only: [:index, :new, :create]
    before_action :find_winery, only: [:show, :edit, :update, :destroy]
    layout "wineries_layout"
    
    def index
        if @region
            @wineries = @region.wineries
        else
            @wineries = Winery.all
        end
    end

    def show
        
    end

    def new
        if @region
            @winery = @region.wineries.build
            render :new_region_winery
        else
            @winery = Winery.new
        end
    end

    def create
        @winery = Winery.new(winery_params)
        if @winery.save
            if @region
                redirect_to region_wineries_path(@region)
            else
                redirect_to wineries_path
            end
        else
            flash.now[:error] = @winery.errors.full_messages
            
            if @region
                render :new_region_winery
            else
                render :new
            end
        end
    end

    def edit

    end

    def update
        if @winery.update(winery_params)
            redirect_to winery_path(@winery)
        else
            flash.now[:error] = @winery.errors.full_messages
            render :edit
        end
    end

    def destroy
        @winery.destroy
        flash[:notice] = "#{@winery.name} was deleted."
        redirect_to wineries_path
    end

    private
        def find_winery
            @winery = Winery.find_by_id(params[:id])
        end

        def find_region
            if params[:region_id]
                @region = Region.find_by_id(params[:region_id])
            end
        end

        def winery_params
            params.require(:winery).permit(:name, :region_id, :website, :phone, region_attributes: [:name])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_nav_links
        content_tag("ul", class: "right hide-on-med-and-down") do
        if user_signed_in?
                content_tag("li") do
                    link_to("Discover Wineries", wineries_path)
                end +
                content_tag("li") do
                    link_to("Add Winery", new_winery_path)
                end +
                content_tag("li") do
                    link_to("Settings", edit_user_registration_path)
                end +
                content_tag("li") do
                    link_to("Logout", destroy_user_session_path, method: "DELETE")
                end
        else
                content_tag("li") do
                    link_to("Login", new_user_session_path)
                end +
                content_tag("li") do
                    link_to("Signup", new_user_registration_path)
                end
            end
        end
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/wineries_helper.rb
module WineriesHelper
    def region_name(winery)
        if winery.region
            winery.region.name
        else
            link_to "Add Region"
        end
    end
end

app/views/layouts/_errors.html.erb
<% if flash[:error] %>
    <div class="red" style="padding 10px;">
        <ul style="margin: 0">
            <% flash[:error].each do |error| %>
                <li><%= error %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= content_tag("p", flash[:notice]) if flash[:notice] %>

app/views/layouts/_nav.html.erb
<div class="navbar-fixed">
        <nav class="<%= navbar_color %>">
        <div class="container">
            <div class="nav-wrapper">
              <a href="/" class="brand-logo">MyCalWineries</a>
              <a href="#" data-target="mobile-nav" class="sidenav-trigger">
                <i class="material-icons">menu</i>
              </a>
            </div>
            <ul class="right">
              <%= render_nav_links %>
            </ul>
        </div>
      </nav>
</div>
      <ul class="sidenav" id="mobile-nav">
        <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, :class => "btn btn-primary", method: "DELETE" %></li>
            <li><%= link_to "Settings", edit_user_registration_path, :class => "btn btn-primary" %></li>
            <li><%= link_to "Add a Winery", new_winery_path, :class => "btn btn-primary" %></li>
            <li><%= link_to "Discover Wineries", wineries_path, :class => "btn btn-primary" %></li>
        <% else %>
            <li><%= link_to "Signup", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
      
      

      <script>
        // Sidenav
        const sideNav = document.querySelector('.sidenav');
        M.Sidenav.init(sideNav, {});

        // Slider
        const slider = document.querySelector('.slider');
        M.Slider.init(slider, {
          indicators: false,
          height: 500,
          transition: 500,
          interval: 6000
        });
      </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCalWineries</title>
    <%= csrf_meta_tags %>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://kit.fontawesome.com/88ad912d1f.js" crossorigin="anonymous"></script>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link href="https://unpkg.com/basscss@8.0.2/css/basscss.min.css" rel="stylesheet">
    <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js?ver=1.4.2'></script>
  </head>

  <body>

      <%= render partial: 'layouts/nav', locals: { navbar_color: "red darken-4" }%>
      <%= render 'layouts/errors' %>
     
      <div class="container">
        <%= yield %>
      </div>

    
  </body>
</html>

app/views/layouts/home_page_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCalWineries</title>
    <%= csrf_meta_tags %>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://kit.fontawesome.com/88ad912d1f.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link href="https://unpkg.com/basscss@8.0.2/css/basscss.min.css" rel="stylesheet">
    <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js?ver=1.4.2'></script>
  </head>

  <body class=" blue lighten-5">
        <div class="container">
            <%= yield %>
        </div>         
  </body>
</html>

app/views/layouts/wineries_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCalWineries</title>
    <%= csrf_meta_tags %>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://kit.fontawesome.com/88ad912d1f.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link href="https://unpkg.com/basscss@8.0.2/css/basscss.min.css" rel="stylesheet">
    <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js?ver=1.4.2'></script>
  </head>

  <body>
    <%= render partial: 'layouts/nav', locals: { navbar_color: "light-blue lighten-4"}%>
      <%= render 'layouts/errors' %>


      <div class="container">
        <%= yield %>
        </div>
    

  </body>
</html>

app/views/regions/index.html.erb
<h2>All Regions</h2>

<ul>
    <% @regions.each do |region| %>
        <li><%= link_to region.name, region_path(region) %></li>
    <% end %>
</ul>

app/views/regions/new.html.erb
<h1>Add a Region</h1>

<%= form_for @region do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <h3>Add a winery associated to that region:</h3>

    <%= f.fields_for :wineries, @region.wineries do |w| %>
    <h4>Winery infos:</h4>
        <br>
        <div>
            <%= w.label :name %>
            <%= w.text_field :name %>
        </div>
        <div>
            <%= w.label :website %>
            <%= w.text_field :website %>
        </div>
        <div>
            <%= w.label :phone %>
            <%= w.telephone_field :phone %>
        </div>
    <% end %>
    <br>
    <%= f.submit %>
<% end %>
<br>

app/views/regions/show.html.erb
<h2><%= @region.name %></h2>

<p><%= link_to "List of Wineries for #{@region.name}", "#" %></p>

app/views/wineries/_form.html.erb
<%= form_for winery do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %><br>
    </div>
    <div>
        <%= f.label :website %>
        <%= f.text_field :website %><br>
    </div>
    <div>
        <%= f.label :phone %>
        <%= f.telephone_field :phone %><br>
    </div>

    <h4>Select Region:</h4>
    <div>
        <%= f.collection_select :region_id, Region.all, :id, :name, include_blank: "Select Region" %>
    </div>

    <h4> Or Add Region:</h4>
    <%= f.fields_for :region, winery.build_region do |region_builder| %>
        <div>
            <%= region_builder.label :name %>
            <%= region_builder.text_field :name %>
        </div>
    <% end %>

    <%= f.submit %>

<% end %>
<br>

<script>
$(document).ready(function(){
    $('select').formSelect();
  });
</script>

app/views/wineries/_winery.html.erb
<div class="col s12 m7">
    <h4 class="header"><%= winery.name %></h4>
    <div class="card horizontal">
      <div class="card-image">
        <img src="https://lorempixel.com/100/190/nature/6">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>Cick on More Information to find out about this winery</p>
        </div>
        <div class="card-action">
          <%= link_to "More Information", winery_path(winery) %>
        </div>
      </div>
    </div>
  </div>

app/views/wineries/edit.html.erb
<h3>Edit <%= @winery.name %></h3>

<%= render partial: "form", locals: { winery: @winery } %>

app/views/wineries/index.html.erb
<h1>List of wineries <%= " for #{@region.name}" if @region %></h1>

<% if @region %>
  <p><%= link_to "Add a winery for #{@region.name}", new_region_winery_path(@region) %>
<% end %>

<ul>
<%= render @wineries %>
</ul>

app/views/wineries/new.html.erb
<h1>Add a winery</h1>

<%= render partial: "form", locals: { winery: @winery } %>

app/views/wineries/new_region_winery.html.erb
<h2>Nested Route for New</h2>

<%= form_for [@region, @winery] do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %><br>
    </div>
    <div>
        <%= f.label :website %>
        <%= f.text_field :website %><br>
    </div>
    <div>
        <%= f.label :phone %>
        <%= f.telephone_field :phone %><br>
    </div>

    <%= f.hidden_field :region_id %>

    <%= f.submit %>
<% end %>

app/views/wineries/show.html.erb
<h1><%= @winery.name %></h1>
<p>Website: <%= @winery.website %></p>
<p>Phone Number: <%= @winery.phone %></p>
<p>Region: <%= region_name(@winery) %></p>

<%= link_to "Edit", edit_winery_path(@winery) %>

<%= link_to "Delete", winery_path(@winery), method: "delete" %>